### ISSUE TITLE
StopIteration error in `get_workflow_results`

### ISSUE THREAD

**Issue by IAlibay** [dwhswenson/ghadash#14]
Thanks for creating this @dwhswenson 

This is probably a user error than a code one, but I tried using this locally and got the following error thrown back to me:

```python
Traceback (most recent call last):
  File "/home/ialibay/software/mambaforge/install/envs/mda-dev/bin/eshgham", line 8, in <module>
    sys.exit(main_exe())
             ^^^^^^^^^^
  File "/home/ialibay/software/mambaforge/install/envs/mda-dev/lib/python3.11/site-packages/eshgham/__main__.py", line 5, in main_exe
    exit(main())
         ^^^^^^
  File "/home/ialibay/software/mambaforge/install/envs/mda-dev/lib/python3.11/site-packages/eshgham/__init__.py", line 304, in main
    sorted_results = runner(gh, workflow_dict)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ialibay/software/mambaforge/install/envs/mda-dev/lib/python3.11/site-packages/eshgham/__init__.py", line 205, in __call__
    result = get_workflow_result(repo, workflow_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ialibay/software/mambaforge/install/envs/mda-dev/lib/python3.11/site-packages/eshgham/__init__.py", line 69, in get_workflow_result
    last_scheduled_run = next(iter(workflow.get_runs(event='schedule')))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration
```

My YAML is as follows:

```yaml
MDAnalysis/mdanalysis:
  - gh-ci.yaml
  - gh-ci-cron.yaml
MDAnalysis/MDAKits:
  - gh-ci-cron.yaml
  - gh-ci.yaml
```

**Comment by dwhswenson** [comment]
Quick guess here, based on the error and the names of the workflows, is that you have some workflows that don't have scheduled runs. I hadn't considered this as a workflow -- ESGHAM is was primarily designed with scheduled runs in mind (it reports last failed/passing scheduled run, or if the schedule is inactive).

It shouldn't be too hard to do *something* for workflows without scheduled runs -- I guess the question is, what's the expected behavior? My intuition was that this could be more confusing because you would need to specify whether you wanted the last run on a PR, or the last run as part of a push to `main`. Getting the last result from a PR could be very uninformative. If the workflow also runs on push to `main` (i.e., when a PR is merged), that result might be the useful one.

The other option would be to disallow non-scheduled workflows, and just give a more informative error here. How much is status of non-scheduled workflows something you need in your use case?

**Comment by IAlibay** [comment]
Ah that makes sense, thanks @dwhswenson ! Happy to use this just on workflows with scheduled runs (better error message could be useful but not essential if it's just for me)
